### ISSUE TITLE
Randomly crashing

### ISSUE THREAD

**Issue by Jollyolsport** [Stereowalker/Survive#142] opened 2021-07-06 05:42 UTC
Not quite sure whats causing the crashes, they happen at seemingly random intervals. 
Forge Version: 36.1.24
Minecraft Version: 1.16.5
Survive Version: 1.16.5-3.3.1
Union Lib Version:  1.16.5-3.3.2

[latest.log](https://github.com/Stereowalker/Survive/files/6767553/latest.log)

**Comment by Onemario1234** [comment] 2021-07-13 20:41
I'm getting this issue as well. Random crashing with no explanation. And I'm too dumb to know what's happening, even with a crash report.

**Comment by Stereowalker** [comment] 2021-08-07 01:23
A bit late, but it doesn't seem to be any of my mods causing the issue

**Comment by Onemario1234** [comment] 2021-08-07 04:49
I can confirm this. The crashing is caused by Configured, it seems.

**Comment by Stereowalker** [comment] 2021-08-07 07:42
Then I can close this?

**Closed as completed** 2021-08-09 09:01 UTC
